<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>AppTheme-AgenceSesame</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="rocketcontentapi.LinksDownload\**" />
    <EmbeddedResource Remove="rocketcontentapi.LinksDownload\**" />
    <None Remove="rocketcontentapi.LinksDownload\**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DNNrocketAPI">
      <HintPath>..\..\..\bin\DNNrocketAPI.dll</HintPath>
    </Reference>
    <Reference Include="RazorEngine">
      <HintPath>..\..\..\bin\RazorEngine.dll</HintPath>
    </Reference>
    <Reference Include="RocketAppThemes">
      <HintPath>..\..\..\bin\RocketAppThemes.dll</HintPath>
    </Reference>
    <Reference Include="RocketContentAPI">
      <HintPath>..\..\..\bin\RocketContentAPI.dll</HintPath>
    </Reference>
    <Reference Include="RocketDirectoryAPI">
      <HintPath>..\..\..\bin\RocketDirectoryAPI.dll</HintPath>
    </Reference>
    <Reference Include="RocketEcommerceAPI">
      <HintPath>..\..\..\bin\RocketEcommerceAPI.dll</HintPath>
    </Reference>
    <Reference Include="RocketIntraMenu">
      <HintPath>..\..\..\bin\RocketIntraMenu.dll</HintPath>
    </Reference>
    <Reference Include="RocketPortal">
      <HintPath>..\..\..\bin\RocketPortal.dll</HintPath>
    </Reference>
    <Reference Include="Simplisity">
      <HintPath>..\..\..\bin\Simplisity.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="rocketcontentapi.Articles\1.0\img\" />
    <Folder Include="rocketcontentapi.Articles\1.0\js\" />
    <Folder Include="rocketcontentapi.Articles\1.0\modt\" />
    <Folder Include="rocketcontentapi.Articles\1.0\resx\" />
    <Folder Include="rocketcontentapi.About\1.0\dep\" />
    <Folder Include="rocketcontentapi.Citation\1.0\dep\" />
    <Folder Include="rocketcontentapi.ContactDetailsSat\1.0\dep\" />
    <Folder Include="rocketcontentapi.Documents\1.0\dep\" />
    <Folder Include="rocketcontentapi.HeroHeader\1.0\dep\" />
    <Folder Include="rocketcontentapi.LeafletMapMultipoint\1.0\dep\" />
    <Folder Include="rocketcontentapi.Links\1.0\dep\" />
  </ItemGroup>

</Project>
